#Milestone-2
MxoDevops/math-magicians pull request #2
Opened 2022-09-10 12:45 UTC by MxoDevops

#Add components
#Add UI
#Updated React App

2022-09-10 12:55 UTC, ahmetbozaci requested changes
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

 @MxoDevops  ✋🏼 

#### Your project is great. You are almost done. However, there are some issues you should fix. Please fix them then your project will be approved.

___ 

### 💯  Highlights 💯
- Your git-flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️
___


### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._
- [ ] Kindly update your README file. 
You can use this [template](https://github.com/microverseinc/readme-template) 
and make sure there are no broken links(screenshot, license, etc.) and empty sections. 
Kindly change the readme template's sentence with your sentence.
![image](https://user-images.githubusercontent.com/38635158/189484310-f0c5edac-a82f-4dde-a1e7-3170b8580357.png)

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-09-10 12:55 UTC, ahmetbozaci commented on src/components/calculator.js
> +  // eslint-disable-next-line class-methods-use-this
- [ ] Kindly don't disable the linter. If giving an error please fix it.

2022-09-13 08:57 UTC, MxoDevops commented
Last week I submitted the 1st-day project of setting up the React app and it got approved. So now I opened this issue to resubmit the setup but I have already deleted the branch that was approved and merged.

2022-09-13 09:13 UTC, brytebee commented
Okay. I have seen the [approved branch here.](https://github.com/MxoDevops/math-magicians/pull/1)

2022-09-13 12:32 UTC, ShoiraTa approved these changes
### **STATUS: APPROVED  ✔️** 
------
Hi @MxoDevops ,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍 
- Project is set up correctly ✔️ 
- Descriptive Pull Request ✔️ 
- No linter errors ✔️ 
- Professional documentation ✔️ 

**OPTIONAL**

- [ ] Please try to write meaningful and descriptive comments. One of the last comments you have is [Made changes](https://github.com/MxoDevops/math-magicians/pull/2/commits/a308bc461fc679cbc11ef240325cede6b290fa17) as you can guess this commit text is not descriptive nor informative

![giphy](https://user-images.githubusercontent.com/77038610/154916093-53a75ff8-ba21-44ad-a25e-bdea6200d8f1.gif)

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-13 13:06 UTC, merged